[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "sh -c \"npx prisma migrate deploy --schema=backend/prisma/schema.prisma && node backend/dist/index.js\""
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
